import type { BlogLang } from "@/lib/blog";

// UNIQUE shared AMF disclaimer, auto-appended to the foot of EVERY article
// (SEO-STRATEGY.md §6 / prompt 2.3). The legal text lives here and only here —
// it is NOT overridable per article. Full legal text, no abbreviated summary
// (golden rule).
//
// Text assembled 2026-07-02 from the already-validated legal copy in
// public/avis-legal.html (discMain + discReg + p1 wording), adapted from
// "cet outil" to "cet article" and extended with the §6 simulated-data
// clause. Review by Maitre before first article publication.
const TEXT: Record<BlogLang, string> = {
  fr: "Cet article est fourni à titre informatif et éducatif seulement. Il ne constitue en aucun cas un conseil financier, fiscal, juridique ou de placement personnalisé. Les données simulées présentées sont des estimations probabilistes générées par simulation Monte Carlo à partir d'hypothèses qui peuvent ne pas se réaliser ; elles ne constituent pas des prévisions de résultats futurs. BuildFi Technologies inc. n'est pas un courtier, un conseiller en placement ni un cabinet de services financiers au sens de la Loi sur la distribution de produits et services financiers (Québec), et n'est pas inscrite auprès de l'Autorité des marchés financiers (AMF) ni d'aucun organisme provincial de réglementation des valeurs mobilières. Consultez un planificateur financier certifié (Pl. Fin.) ou un conseiller autorisé avant de prendre toute décision financière importante.",
  en: "This article is provided for informational and educational purposes only. It does not constitute personalized financial, tax, legal, or investment advice. Any simulated data presented are probabilistic estimates generated by Monte Carlo simulation from assumptions that may not materialize; they do not constitute predictions of future results. BuildFi Technologies inc. is not a broker, investment advisor, or financial services firm under Quebec's Financial Products and Services Distribution Act, and is not registered with the Autorité des marchés financiers (AMF) or any provincial securities regulatory authority. Consult a certified financial planner or licensed advisor before making any important financial decision.",
};

export default function DisclaimerAMF({ lang }: { lang: BlogLang }) {
  return (
    <footer className="bf-disclaimer">
      <p>{TEXT[lang]}</p>
    </footer>
  );
}
